---
title: エラーの比較
tags:
  - Go
private: true
updated_at: '2024-09-02T20:30:30+09:00'
id: 3921d2900a60bb8e9c88
organization_url_name: null
slide: false
ignorePublish: false
---
# エラー型の比較

IDから取引金額を返すHTTPハンドラを実装する。そのハンドラは、リクエストを解析してIDを取得し、データベースから金額を取得する。この実装は2つのケースで失敗する可能性がある。

* IDが不正なケース(文字列の長さが5文字以上)
* DBへのクエリが失敗するケース

前者では、400(StatusBadRequest)、後者は503(ServiceUnavailable)を返す。そのため、エラーが一時的であることをマークするため、transientError型を作成する。親ハンドラはそのエラー型を検査する。もし、エラーがtransientErrorであれば、503を返し、そうでなければ400エラーを返すようにする。

```go
type transientError struct {
	err error
}

func (t transientError) Error() string {
	return fmt.Sprintf("transient error: %v", t.err)
}

func getTransactionAmount(transactionID string) (float32, error) {
	if len(transactionID) != 5 {
         // transactionIDが不正のときは単純なエラーを返す
		return 0, fmt.Errorf("id is invalid: %s", transactionID)
	}

	amount, err := getTransactionAmountFromDB(transactionID)
	if err != nil {
         // DBへのクエリが失敗したら、transientErrorを返す
		return 0, transientError{err: err}
	}
	return amount, nil
}

func getTransactionAmountFromDB(id string) (float32, error) {
	return 0, nil
}
```

getTransactionAmountはtransactionIDが不正の時、fmt.Errorfでエラーを返す。
DBからの取引金額の取得に失敗したとき、getTransactionAmountはエラーをtransientError型にラップしている。

エラー型を検査するHTTPハンドラは以下のようになる。

```go
func handler(w http.ResponseWriter, r *http.Request) {
	transactionID := r.URL.Query().Get("transaction")

	amount, err := getTransactionAmount(transactionID)
	if err != nil {
         // transientErrorの時は503、それ以外は400を返す
		switch err := err.(type) {
		case transientError:
			http.Error(w, err.Error(), http.StatusServiceUnavailable)
		default:
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
		return
	}

	// Write response
	_ = amount
}
```

これは妥当なコードであるが、リファクタする。

```go
func getTransactionAmount(transactionID string) (float32, error) {
	// transactionIDの正当性を検査する
	amount, err := getTransactionAmountFromDB2(transactionID)
	if err != nil {
         // transientErrorを直接返す代わりに、エラーをラップする
		return 0, fmt.Errorf("failed to get transaction %s: %w",
			transactionID, err)
	}
	return amount, nil
}

func getTransactionAmountFromDB(transactionID string) (float32, error) {
	// ...
	var err error
	if err != nil {
		return 0, transientError{err: err}
	}
	// ...
	return 0, nil
}
```

このようにすることで、handler関数はエラー型に関係なく、400を返し、case transientErrorに該当することはない。

getTransactionAmountはtransientErrorがfalseになる。

ラップされたエラーが特定の型か否か検査する`errors.As()`がある。`errors.As()`はエラーを再起的にアンラップし、連鎖したエラーが期待する型に一致する場合にtrueを返す。

```go
func handler(w http.ResponseWriter, r *http.Request) {
	transactionID := r.URL.Query().Get("transaction")

	amount, err := getTransactionAmount(transactionID)
	if err != nil {
		if errors.As(err, &transientError{}) {
			http.Error(w, err.Error(), http.StatusServiceUnavailable)
		} else {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
		return
	}

	// Write response
	_ = amount
}
```

switchを使わずに`errors.As()`を用いている。この関数は、第２引数(対象エラー)がポインタである必要がある。ポインタでないと、この関数の呼び出しはコンパイルはできるが、実行時にpanicとなる。実行時エラーが直接transientError型かtransientErrorをラップしたエラーであっても、`errors.As()`はtrueを返す。ゆえに、ハンドラは503というステータスコードを返す。


Go1.13のエラーラッピングに依存する場合、エラーが特定の型か否かを検査するために`errors.As()`を使用する必要がある。

# エラー値の比較

## センチネルエラー

センチネルエラー(sentinel error) : グローバル変数として定義されたエラー

```go
impoprt "errors"

var ErrFoo = errors.New("foo")
```

一般的に、ErrXXXといった命名が慣例となっている。センチネルエラーは予期されるエラーを伝えるもの。

DBに対するクエリを実行するためのQueryメソッドを設計する。このメソッドは行のスライスを返す。行が見つからない場合は以下2つの選択肢がある。

* センチネル値を返す。例えば、nilスライス(strings.Indexは部分文字列が存在しない場合、センチネル値-1を返すと考える)
* クライアントが検査可能な特定のエラーを返す

2つ目の方法では、行が見つからないとき、このメソッドは特定のエラーを返せる。行を返さないリクエストを渡すことは許されているので、これは**予期されるエラー**に分類できる。
逆にネットワーク問題や接続のポーリングエラーのような状況は**予期されないエラー**となる。これは、予期されないエラーを処理したくないのではなく、これらのエラーは異なる意味を伝えるもの。

標準ライブラリの例を挙げると、

* sql.ErrNoRows : クエリが行を返さなかった場合に返される
* io.EOF : 入力がなくなったときにio.Reader

これがセンチネルエラーの一般的な原則。クライアントが検査することを期待する、予期されるエラーを伝えること。以下が一般的なガイドラインとなる。

* 予期されるエラーは、エラー値(センチネルエラー)として設計する(e.g. `var ErrFoo = errors.New("foo")
* 予期されないエラーは、エラー型として設計する(e.g. `type BarError struct {...}` とし、BarErrorはerrorインターフェイスを実装する)


## エラーと特定の値の比較

まず、`==`を使用する例を挙げる。

```go
func foo() {
	err := query()
	if err != nil {
		if err == sql.ErrNoRows {
			// ...
		} else {
			// ...
		}
	}
}
```

query関数を呼び出して、エラーを取得している。センチネルエラーもラップできる。`fmt.Errorf`と`%w`を使ってsql.ErrNoRowsをラップすると、`err == sql.ErrNoRows` は常に*false*になる。

Go1.13で、エラー値を検査する`errors.Is`を使えるようになった。


```go
func foo() {
	err := query()
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			// ...
		} else {
			// ...
		}
	}
}
```

ゆえに、`==`を使用せずに、errors.Isを用いる。すると、ラップされていても比較できる。センチネルエラーがラップされていても`errors.Is`を使用すると、再起的にアンラップして、連鎖した各エラーと与えられた値を比較できる。

