---
title: エラーラッピング
tags:
  - Go
private: true
updated_at: '2024-08-30T21:40:47+09:00'
id: 50c4830ec5d31da831f7
organization_url_name: null
slide: false
ignorePublish: false
---

# エラーラッピング

Go v1.13以上では`%w`verbでエラーを便利にラップできる。

:::note info
Goでは書式指定子をverbと呼ぶ。
:::

# エラーラッピングの目的

* エラーに文脈情報を追加する
* エラーを特定エラーとしてマークする

# エラーラッピングとは？

エラーラッピングはエラーをラップして、元のエラーも利用できるようにすること。

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/098a832b-f8d0-885c-8223-47fb9b6fb4b4.png)

# エラーラッピングの例

特定のユーザからデータベース資源へのアクセスようう急を受けたが、クエリ中に「パーミッションが拒否されました」というエラーが発生するとき。デバッグのためには、エラーを最終的にログに記録されるように、文字情報を追加したい。この場合は以下のように、エラーをラップして、そのユーザが誰か、どの資源にアクセスしているかを示す。

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/20fb0027-84ae-8811-24c8-6e0316923036.png)

ここで文脈情報を追加する代わりに、エラーにマークをつけたい。
関数を呼び出したときに受けとったすべてのエラーがForbidden型稼働化を検査するHTTPハンドラを実装して、403を返すようにする。

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/debec21c-6cdb-c581-850e-e47e26f09908.png)


どちらの場合も、元エラーは利用可能なままである。
呼び出しもとは、エラーをアンラップして、元のエラーを検査することで、エラーを処理することができる。文脈情報を追加した上で、マーク付けをするという両方の情報を孵化したい場合もある。

# エラーの返し方

```go
func foo() error {
	err := bar()
	if err != nil {
		// どうやってエラーを返すでしょう？
	}
	// do something
}
```

## ラップしない

```diff_go
func foo() error {
	err := bar()
	if err != nil {
+ 		return err
	}
	// do something
}
```

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/3af4f170-5871-ce8b-a753-9cc7f9345205.png)


## bar

```diff_go
func foo() error {
	err := bar()
	if err != nil {
+ 		return err
	}
	// do something
    return nil
}
```

## 独自のエラー型を生成する

Go1.13より前のバージョンでは、外部ライブラリを使わずにエラーをラップするには、独自のエラー型を生成するのが唯一の方法。

```diff_go
func bar() error {
	return barError{}
}

type barError struct{}

func (b barError) Error() string {
	return "bar error"
}

type BarError struct {
	Err error
}

func (b BarError) Error() string {
	return "bar failed:" + b.Err.Error()
}

func foo() error {
	err := bar()
	if err != nil {
+ 		return BarError{Err:err}
	}
	// do something
    return nil
}
```

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/6070808b-ccd6-0850-ae84-2c8604c88c7e.png)

このようにすると柔軟性が高まる。BarErrorは独自の構造体のため、必要に応じて、文脈情報を追加できる。しかし、エラー型を作成する必要があるため、この操作を繰り返すと、面倒なことになる。(ゆえに`%w`verbが導入された。)

## %wを利用する

```diff_go
func foo() error {
	err := bar()
	if err != nil {
+		return fmt.Errorf("bar failed: %w", err)
	}
	// do something
	return nil
}
```

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/73316e53-f553-67b0-784d-231350e2a076.png)


## %vを利用する

```diff_go
func foo() error {
	err := bar()
	if err != nil {
+		return fmt.Errorf("bar failed: %v", err)
	}
	// do something
	return nil
}
```

`%w`との違いはエラーそのものがラップされていないこと。
文脈情報を追加するためにそのエラーを別のエラーに変換すると、元のエラーは利用できなくなる。
呼び出しもとはエラーをアンラップできず、元のエラーがbarエラーであったかを検査できない。

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/156096/9db95ad2-c13c-2578-af63-df25c4989528.png)


`%w`より制限されているが、必ずしも`%w`を使ったほうがいいとは限らない。
エラーをラップすると、呼び出し元が元のエラーを利用できるが、それはコードの結合という潜在的な問題を導入してしまう。

エラーラッピングを使って元のエラーがbarエラーかどうかをFooの呼び出し元が検査する場合を考える。その上で実装を変更して、別の関数を使い、別の種類のエラーを返すようにすると、呼び出し元が行なったエラーの検査が機能しなくなる。

クライアントが実装の詳細と考えられるものに依存しないようにするには、返されるエラーはラップされるのではなく、変換される必要がある。このような場合は`%w`ではなく、`%v`を使用するのが好ましい。

## エラーラッピングの方法まとめ

| 方法 | 追加の文脈情報 | エラーのマーク付け | 元のエラーが利用可能 |
|:-:|:-:|:-:|:-:|
| エラーを直接返す  |  ❌ |  ❌ |  ⭕️ |
|  独自のエラー型 | ⭕️(エラー型が文字列フィールドを含んでいたら)  | ⭕️  | ⭕️(元のエラーが公開されている、メソッドを通してアクセスできるなら可能)  |
| fmt.Errorfと%w  |  ⭕️ | ❌  | ⭕️  |
| fmt.Errorfと%v  |  ⭕️ | ❌  | ❌  |
