---
title: エラーを処理しない
tags:
  - Go
private: true
updated_at: '2024-09-02T21:01:48+09:00'
id: d885e5778112416327fb
organization_url_name: null
slide: false
ignorePublish: false
---
# エラーの無視

次の例は、1つのエラーを返すnotify()をコールしている。エラーに興味がないので、エラー処理を意図的に省いている。

```go
func f() {
	// ...

	notify() //エラー処理を省いている
}

func notify() error {
	return errors.New("failed to notify")
}
```

Goでエラーを無視したい場合は方法は1つだけ。

```go
_ = notify()
```

コメントをつけるのも冗長。
